apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tgrunner
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tgrunner
            image: coryschwartz/tgrunner:latest
            env:
            - name: DAEMON
              value:
            - name: GITREPO
              value:
            - name: PLAN
              value:
            - name: TESTCASE
              value:
            - name: INSTANCES
              value:
            - name: NAME
              value:
            - name: KOPS_STATE_STORE
              value:
            - name: AWS_DEFAULT_REGION
              value:
            - name: AWS_SECRET_ACCESS_KEY
              value:
            - name: AWS_ACCESS_KEY_ID
              value:
            - name: AWS_REGION
              value:
          restartPolicy: OnFailure
