---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: drand-cluster-kops.k8s.local
  name: nodes
spec:
  additionalUserData:
  - name: myscript.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      cat <<EOT >> /etc/sysctl.d/999-testground.conf
      net.core.somaxconn = 131072
      net.netfilter.nf_conntrack_max = 1048576
      net.ipv4.tcp_max_syn_backlog = 131072
      net.core.netdev_max_backlog = 524288
      net.ipv4.ip_local_port_range = 10000 65535
      net.ipv4.tcp_tw_recycle = 1
      net.ipv4.tcp_tw_reuse = 1
      net.core.rmem_max = 4194304
      net.core.wmem_max = 4194304
      net.ipv4.tcp_mem = 262144 524288 1572864
      net.ipv4.tcp_rmem = 16384 131072 4194304
      net.ipv4.tcp_wmem = 16384 131072 4194304
      net.ipv4.neigh.default.gc_thresh2 = 4096
      net.ipv4.neigh.default.gc_thresh3 = 32768
      EOT
  cloudLabels:
    testground.nodetype: plan
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: c5.2xlarge
  maxSize: 8
  minSize: 8
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
    testground.nodetype: plan
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b

